name: CI

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore and Test Expenses Solution
        run: |
          dotnet restore server/services/expenses/Expenses.slnx
          dotnet build server/services/expenses/Expenses.slnx --no-restore --configuration Release
          dotnet test server/services/expenses/Expenses.slnx --no-build --configuration Release